


baseURL = "https://jimmy-sheng.github.io/"
languageCode = "en-gb"
title = "Jimmy Sheng"
theme = "PaperMod"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[languages]

  [languages.en]
    languageName = "English"
    weight = 1

    [[languages.en.menu.main]]
      name = "Home"
      url = "/"
      weight = 1

    [[languages.en.menu.main]]
      name = "About Me"
      url = "/about/"
      weight = 2

    [[languages.en.menu.main]]
      name = "Experience"
      url = "/experience/"
      weight = 3

    [[languages.en.menu.main]]
      name = "Projects"
      url = "/projects/"
      weight = 4

  [languages.zh]
    languageName = "繁體中文"
    weight = 2

    [[languages.zh.menu.main]]
      name = "首頁"
      url = "/"
      weight = 1

    [[languages.zh.menu.main]]
      name = "關於我"
      url = "/about/"
      weight = 2



